os: linux
dist: bionic
language: generic
git:
  depth: 1
addons:
  apt:
    update:
      - true
install: false || true
script:
  - "travis_wait 30 sleep 2400 &"
  - git config --global user.email $GitHubMail
  - git config --global user.name $GitHubName
  - git config --global color.ui true
  - git clone https://github.com/rokibhasansagar/aosp_kernel_mediatek.git -b android-3.18 $TRAVIS_BUILD_DIR/kernel/
  - cd $TRAVIS_BUILD_DIR/
  - git clone https://android.googlesource.com/kernel/mediatek -b android-3.18 --single-branch renewed_kernel_mediatek/
  - rm -rf renewed_kernel_mediatek/.git
  - cd $TRAVIS_BUILD_DIR/kernel/
  - rm -rf *
  - cp -a $TRAVIS_BUILD_DIR/renewed_kernel_mediatek/* .
  - rm -rf $TRAVIS_BUILD_DIR/renewed_kernel_mediatek/
  - git add -A .
  - git commit -m "Release 3.18.y MediaTek Kernel Source at $(date +%Y%m%d-%H%M)" || echo -e "All files are identical, No need to push new files"
  - git push --force https://$GitOAUTHToken@github.com/rokibhasansagar/aosp_kernel_mediatek.git HEAD:android-3.18
branches:
  only:
    - master
  except:
    - /^(?i:untagged)-.*$/
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
